/*
** EPITECH PROJECT, 2020
** IGamePadModule.hpp
** File description:
** header for IGamePadModule.c
*/

#ifndef PLUGIN_TEMPLATE_IGAMEPADMODULE_HPP
#define PLUGIN_TEMPLATE_IGAMEPADMODULE_HPP

#endif //PLUGIN_TEMPLATE_IGAMEPADMODULE_HPP
